version: "3.9"
services:
  api:
    build: ./docker
    ports: ["8080:8080"]
    env_file: ["../.env"]
    environment:
      CHROMA_DB_DIR: /app/data/chroma
    volumes:
      - ../app:/app/app
      - ../scripts:/app/scripts
      - ../data:/app/data
    command: bash -c "python scripts/bootstrap.py && python scripts/ingest_guard.py && python -m uvicorn app.main:app --host 0.0.0.0 --port 8080"

