services:
  api:
    build:
      context: ..                 # repo root
      dockerfile: docker/Dockerfile
    container_name: ai-incident-api
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      CHROMA_DB_DIR: /app/data/chroma
      AUDIT_DIR: /app/data/logs
      DUCK_DB_PATH: /app/data/logs/security.duckdb
    volumes:
      - ../app:/app/app
      - ../scripts:/app/scripts
      - ../data:/app/data
      - ../frontend:/app/frontend
      - ../requirements.txt:/app/requirements.txt:ro
    command: >
      bash -c "
        python scripts/bootstrap.py &&
        python scripts/ingest_guard.py &
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8080
      "
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 3s
      retries: 30

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ai-incident-ui
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    environment:
      BACKEND_URL: http://api:8080           # UI -> API via Docker DNS
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
    volumes:
      - ../frontend:/app/frontend
      - ../requirements.txt:/app/requirements.txt:ro
    command: >
      bash -c "
        streamlit run /app/frontend/streamlit_app.py
        --server.port ${STREAMLIT_SERVER_PORT:-8501} --server.address 0.0.0.0
      "

