services:
  api:
    build:
      context: ..                 # repo root
      dockerfile: docker/Dockerfile
    container_name: ai-incident-api
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      CHROMA_DB_DIR: /app/data/chroma
      AUDIT_DIR: /app/data/logs
      DUCK_DB_PATH: /app/data/logs/security.duckdb
    volumes:
      - ../app:/app/app
      - ../scripts:/app/scripts
      - ../data:/app/data
      - ../frontend:/app/frontend
      - ../requirements.txt:/app/requirements.txt:ro
    command: >
      bash -c "
        python scripts/bootstrap.py &&
        python scripts/ingest_guard.py &
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8080
      "
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    image: node:22-alpine
    container_name: ai-incident-web
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://api:8080
    volumes:
      - ../frontend:/app
    command: sh -lc "npm ci || npm install && npm run dev -- --host"
    depends_on:
      api:
        condition: service_healthy

