version: "3.9"
services:
  web:
    build: ./docker
    ports:
      - "${PORT-8080}:8080"
    env_file:
      - ../.env           # uses the same root .env for Docker runs
    volumes:
      - ../app:/app/app   # live-reload style mapping for dev
    command: ["python", "app/main.py"]

