version: "3.9"

services:
  api:
    build:
      context: ..                 # <-- repo root as build context
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      CHROMA_DB_DIR: /app/data/chroma
      AUDIT_DIR: /app/data/logs
      DUCK_DB_PATH: /app/data/logs/security.duckdb
    volumes:
      - ../app:/app/app
      - ../scripts:/app/scripts
      - ../data:/app/data
    command: >
      /bin/sh -c "
      python scripts/bootstrap.py &&
      python scripts/ingest_guard.py &&
      python -m uvicorn app.main:app --host 0.0.0.0 --port 8080
      "
